<a href="https://colab.research.google.com/github/GabrielBatavia/Learn_TensorFlow/blob/main/00_learn_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import TensorFlow for first learning

import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [ ]:
# Create a Vector

vector =  tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimensions of the vector

vector.ndim

1

In [ ]:
# Create a matrix (has more dimensions)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check dimensions of the matrix

matrix.ndim

2

In [ ]:
# Create another matrix

matrix_2 = tf.constant([[10.2,7.],[7.,10.2],[10.,7.2]], dtype = tf.float16) #spesify data type with parameter
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.2,  7. ],
       [ 7. , 10.2],
       [10. ,  7.2]], dtype=float16)>

In [ ]:
# Check dimensions of the other matrix

matrix.ndim

2

In [ ]:
# Lets create tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we create so far?

* Scaler = is a single number
* Vector = a number with direction (e.g wind speed)
* matrix = a 2 dimensional array of numbers
* tensor = an n-dimensional arrays of numbers (n can be any numbers ; 0-dimensional tensor is scaler, 1-dimensional tensor is vector, 2-dimensional tensor is matrix )

### Creating tensor with tf.Variable

In [ ]:
# create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# change the elemen in changeable tensor

# changeable_tensor[0] = 7  #This way will make erorr

#try use .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# lets try change unchangeable_tensor

#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

# will make error cause const cant change

What we create so far?

tf.constant = is a constant tensor that we cant change the value
tf.Variable = is a changeable tensor

.assign() = the syntax for change the value of the changeable tensor

### Create random tensors

random tensors are tensors of some abitrary size which contain random numbers

In [ ]:
# create two random (but same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
#  are they equal?

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [ ]:
# shuffle a tensor (valuable if we want shuffle a data so the inherent order dosent effect learning)

not_shuffled = tf.constant([[10,7],
                            [13,2],
                            [7,9]])
#not_shuffled.ndim

# shuffle our non_shuffled tensor
#tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  9],
       [10,  7],
       [13,  2]], dtype=int32)>

⚡**EXERCISE** : read this documentation for set_seed https://www.tensorflow.org/api_docs/python/tf/random/set_seed , and practice writing 5 random tensors and shuffle them

In [ ]:
# Exercise 1

tensor_exercise1 = tf.constant([[1,2],
                                 [3,4],
                                 [5,6]])

tf.random.shuffle(tensor_exercise1, seed=23)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# Exercise 2

tensor_exercise2 = tf.constant([[[1,2],
                                  [3,4]],
                                 [[5,6],
                                  [7,8]],
                                 [[9,10],
                                 [11,12]]])

tf.random.set_seed(12) # global level seed
tf.random.shuffle(tensor_exercise2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [ ]:
shuffle_tensor1 = tf.random.shuffle(tensor_exercise2, seed=42)

In [ ]:
shuffle_tensor2 = tf.random.shuffle(tensor_exercise2, seed=42)

In [ ]:
#check if it equal
shuffle_tensor1 == shuffle_tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=bool, numpy=
array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])>

In [ ]:
# Exercise 3

tensor_exercise3 = tf.random.Generator.from_seed(12)
tensor_exercise3 = tensor_exercise3.normal(shape = (3,2))

tensor_exercise3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967],
       [ 0.37944323, -0.6664026 ]], dtype=float32)>

In [ ]:
tf.random.shuffle(tensor_exercise3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.37944323, -0.6664026 ],
       [ 1.2132233 ,  0.46988967],
       [-1.0130816 ,  0.28291714]], dtype=float32)>

In [ ]:
# Exercise 4

tensor_exercise4 = tf.random.Generator.from_seed(42)
tensor_exercise4 = tensor_exercise4.normal(shape=(4,2,4))

tensor_exercise4

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]]],
      dtype=float32)>

In [ ]:
tf.random.shuffle(tensor_exercise4)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]]],
      dtype=float32)>

In [ ]:
# Exercise 5

tensor_exercise5 = tf.random.Generator.from_seed(42)
tensor_exercise5 = tensor_exercise5.normal(shape=(2,8,3))

tensor_exercise5

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]]], dtype=float32)>

In [ ]:
tf.random.shuffle(tensor_exercise5)

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]],

       [[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]]], dtype=float32)>

### Other ways to create tensor

In [ ]:
# create tensor of all ones

tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensor of all zeroes

tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main deferent between numpy arrays and tensors is tensors can run in GPU (Fasters)

In [ ]:
# You can also turn numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix)  #capital for matrix or tensors
# y = tf.constant(vector)       #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A) # its will be tensors
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape=(4,3,2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors, we probably want to know the following atribut :
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# index tensor

rank_4_tensor[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
# check the shape, rank, and size

rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors

Tensors can be indexing just like pyton list

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# Add extra dimension to our tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [ ]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulating Tensors (Tensor Operation)

**Basic Operation**

In [ ]:
# Add values to tensors using addition operation

tensor_op_1 = tf.constant([[10,7],
                           [3,4]])
tensor_op_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# check the value
tensor_op_1 # the value dosent change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication

tensor_op_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction

tensor_op_1 - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-90, -93],
       [-97, -96]], dtype=int32)>

In [ ]:
#

tensor_op_1 / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [ ]:
# Use the tensorflow built-in function

tf.multiply(tensor_op_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multipication

In machine learning, matrix multipication is one common tensor operations

Two rules :
1. The inner dimensions must match
2. The resulting matrix has shape of the outer dimensions

for the example : if we have 3,2 and 2,3 matrix <br>
the "3" from the first matrix and "3" from the second is the outer<br>
the "2" from the first matrix and "2" from the second is the inner

In [ ]:
 # Matrix multiplication in tensorflow

 print(tensor_op_1)
 tf.matmul(tensor_op_1, tensor_op_1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operatot "@"

tensor_op_1 @ tensor_op_1

# Just can use if the matrix shape([2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# create a example tensor (little exercise)

tensor1 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])

tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])

In [ ]:
# multyply the tensor

tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# try to reshape

tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:
# We can do same with transpose

tf.transpose(tensor2) # have deferent output from the reshape cause its flip the axis

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [ ]:
# try by my self

tf.matmul(tf.transpose(tensor1), tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 24, 33],
       [21, 21, 21],
       [22, 40, 27]], dtype=int32)>

### The dot Product

Matrix multiplication is also referred to as the dot product

We can perform matrix multiplication with :
* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# make the tensor first

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [ ]:
# Perform the dot product  on X and Y (requires the X and Y to be transposed)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshape)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transpose Y

print("Normal Y:")
print(Y, "\n ")

print("Y reshaped to (2, 3) :")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed :")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 
 
Y reshaped to (2, 3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing multiplication, we will transpose (rather than reshape)

###  Changing the datatype of a tensor

In [ ]:
tf.__version__

'2.15.0'

In [ ]:
# create new tensor with default datatype (float32)

A = tf.constant([1.2, 5.7])
A.dtype


tf.float32

In [ ]:
# create new tensor with default datatype (int32)

B = tf.constant([2,3])
B.dtype

tf.int32

In [ ]:
# Change from float32 to float16 (reduced precision)

A = tf.cast(A, dtype=tf.float16)
A.dtype

tf.float16

In [ ]:
# Change ftom int32 to int16

B = tf.cast(B, dtype=tf.int16)
B.dtype

tf.int16

### Aggregating Tensors

Aggregating tensors = condesing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Following forms of aggregation :**

* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [ ]:
# Find the min

tf.math.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [ ]:
# Find the max

tf.math.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [ ]:
# find the mean

tf.math.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [ ]:
# Find the sum

tf.math.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [ ]:
# create random tensor with values between 0 and 100

random_tensor = tf.constant(np.random.randint(0,100, size=150))
random_tensor

<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([97, 45, 44, 13, 20, 47, 49,  7, 15,  5, 50, 89, 93, 58, 84, 10, 76,
       28, 69, 45, 79, 15, 87, 45, 36, 24, 16, 34, 17, 21, 35,  7, 85, 35,
        4, 76, 39, 24, 55, 43, 93, 69,  3, 17, 37, 57, 60, 11, 48, 59, 40,
        7, 85, 35, 47, 52,  6, 93, 93, 42, 89, 68, 40, 68, 88, 34, 30, 66,
       43, 34, 28, 29, 25,  7, 47, 88, 26, 71, 72, 43, 33,  0, 15, 83, 40,
       79, 94, 78, 75, 23, 32, 37, 56, 68, 38,  8, 57, 61, 70, 64,  8, 22,
       36, 20, 42, 75, 47, 67, 33, 42, 58, 93, 75, 43, 80, 33, 83, 76, 34,
       87, 79, 46, 33, 70, 36, 60, 80, 21,  5, 61, 23, 57, 83, 93, 27, 44,
       77,  0, 73, 41, 72, 45, 22,  1, 87, 12, 26, 64, 69, 46])>

In [ ]:
tf.size(random_tensor), random_tensor.ndim, random_tensor.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=150>, 1, TensorShape([150]))

In [ ]:
# Find the min

tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# Find the max

tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# Find the mean

tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [ ]:
# Find the sum

tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=7189>

⚡**EXERCISE** : Find the variance and standard deviation of our random_tensor

In [ ]:
# import tfp for find variance

import tensorflow_probability as tfp

In [ ]:
# Find the variance

tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=712>

In [ ]:
# but we can just use tf to find variance but its must in float (real or complex tensor)

tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=711.8279555555555>

In [ ]:
# Find the standard deviation

tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=26.680104114406216>

### Find the Positional maximum and minimum

In [ ]:
# create new tensor

tensorA = tf.constant(np.random.randint(0,15, size=50))
tensorA

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 5,  1, 12,  2,  3, 11, 10,  2,  8,  4,  4,  9,  3,  9,  2, 11,  9,
       13,  4, 13,  0,  4,  7,  0,  4,  9,  9,  3, 14,  0,  1,  9,  1,  9,
        7,  0, 13, 13, 10,  1, 14,  1,  5,  4,  8,  1,  6,  4,  0,  6])>

In [ ]:
# Find positional maximum

tf.argmax(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=28>

In [ ]:
# index the large value

tensorA[tf.argmax(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [ ]:
# Find positional minimum

tf.argmin(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=20>

In [ ]:
# Index the smallest value

tensorA[tf.argmin(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# just create a random tensor

random1 = tf.constant(np.random.randint(0, 15, size=10))
random2 = tf.constant(np.random.randint(0,15, size=10))

print(random1, random2)

tf.Tensor([13  7 10 11 13  9  1 11  6  8], shape=(10,), dtype=int64) tf.Tensor([ 0 10 14  1  9  2  9 12 12  2], shape=(10,), dtype=int64)


In [ ]:
# Find positional maximum

tf.math.maximum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([13, 10, 14, 11, 13,  9,  9, 12, 12,  8])>

In [ ]:
# Find positional minimum

tf.math.minimum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 0,  7, 10,  1,  9,  2,  1, 11,  6,  2])>

In [ ]:
# create more example

random3 = tf.constant([[[1,2],
                       [3,8]],
                       [[9,2],
                        [7,3]]])

random4 = tf.constant([[[3,8],
                       [9,10]],
                       [[29,4],
                        [4,8]]])

random3, random4

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 8]],
 
        [[9, 2],
         [7, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 3,  8],
         [ 9, 10]],
 
        [[29,  4],
         [ 4,  8]]], dtype=int32)>)

In [ ]:
# Find positional maximum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

In [ ]:
# Find positional minimum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

### Squeezing a tensor (removing all single dimensions)

In [193]:
# Create a tensor to get started

G = tf.constant(tf.random.uniform(shape=[50]), shape=(2, 1, 1, 1, 25))
G

<tf.Tensor: shape=(2, 1, 1, 1, 25), dtype=float32, numpy=
array([[[[[0.5575535 , 0.5520891 , 0.13934886, 0.33942223, 0.07948232,
           0.81038344, 0.8485956 , 0.29627264, 0.5450822 , 0.5916791 ,
           0.2625519 , 0.57897174, 0.39981687, 0.6733477 , 0.8567344 ,
           0.80716884, 0.1496445 , 0.3576498 , 0.03192794, 0.36249554,
           0.50792575, 0.2192378 , 0.8268355 , 0.81314695, 0.8304304 ]]]],



       [[[[0.5390252 , 0.19966578, 0.44580126, 0.09663618, 0.89214504,
           0.44151068, 0.36325562, 0.53622234, 0.35314202, 0.49861085,
           0.543877  , 0.17917085, 0.9940715 , 0.66294503, 0.19296443,
           0.61846256, 0.04284346, 0.70889544, 0.5312805 , 0.7178627 ,
           0.57905793, 0.54222727, 0.37346053, 0.91493416, 0.8788043 ]]]]],
      dtype=float32)>

In [194]:
G.shape

TensorShape([2, 1, 1, 1, 25])

In [196]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.5575535 , 0.5520891 , 0.13934886, 0.33942223, 0.07948232,
         0.81038344, 0.8485956 , 0.29627264, 0.5450822 , 0.5916791 ,
         0.2625519 , 0.57897174, 0.39981687, 0.6733477 , 0.8567344 ,
         0.80716884, 0.1496445 , 0.3576498 , 0.03192794, 0.36249554,
         0.50792575, 0.2192378 , 0.8268355 , 0.81314695, 0.8304304 ],
        [0.5390252 , 0.19966578, 0.44580126, 0.09663618, 0.89214504,
         0.44151068, 0.36325562, 0.53622234, 0.35314202, 0.49861085,
         0.543877  , 0.17917085, 0.9940715 , 0.66294503, 0.19296443,
         0.61846256, 0.04284346, 0.70889544, 0.5312805 , 0.7178627 ,
         0.57905793, 0.54222727, 0.37346053, 0.91493416, 0.8788043 ]],
       dtype=float32)>,
 TensorShape([2, 25]))