<a href="https://colab.research.google.com/github/GabrielBatavia/Learn_TensorFlow/blob/main/00_learn_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import TensorFlow for first learning

import tensorflow as tf
print(tf.__version__)

2.15.0


In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [4]:
# Create a Vector

vector =  tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check dimensions of the vector

vector.ndim

1

In [6]:
# Create a matrix (has more dimensions)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check dimensions of the matrix

matrix.ndim

2

In [8]:
# Create another matrix

matrix_2 = tf.constant([[10.2,7.],[7.,10.2],[10.,7.2]], dtype = tf.float16) #spesify data type with parameter
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.2,  7. ],
       [ 7. , 10.2],
       [10. ,  7.2]], dtype=float16)>

In [9]:
# Check dimensions of the other matrix

matrix.ndim

2

In [10]:
# Lets create tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we create so far?

* Scaler = is a single number
* Vector = a number with direction (e.g wind speed)
* matrix = a 2 dimensional array of numbers
* tensor = an n-dimensional arrays of numbers (n can be any numbers ; 0-dimensional tensor is scaler, 1-dimensional tensor is vector, 2-dimensional tensor is matrix )

### Creating tensor with tf.Variable

In [12]:
# create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# change the elemen in changeable tensor

# changeable_tensor[0] = 7  #This way will make erorr

#try use .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# lets try change unchangeable_tensor

#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

# will make error cause const cant change

What we create so far?

tf.constant = is a constant tensor that we cant change the value
tf.Variable = is a changeable tensor

.assign() = the syntax for change the value of the changeable tensor

### Create random tensors

random tensors are tensors of some abitrary size which contain random numbers

In [15]:
# create two random (but same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [16]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [17]:
#  are they equal?

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [18]:
# shuffle a tensor (valuable if we want shuffle a data so the inherent order dosent effect learning)

not_shuffled = tf.constant([[10,7],
                            [13,2],
                            [7,9]])
#not_shuffled.ndim

# shuffle our non_shuffled tensor
#tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  9],
       [13,  2],
       [10,  7]], dtype=int32)>

⚡**EXERCISE** : read this documentation for set_seed https://www.tensorflow.org/api_docs/python/tf/random/set_seed , and practice writing 5 random tensors and shuffle them

In [19]:
# Exercise 1

tensor_exercise1 = tf.constant([[1,2],
                                 [3,4],
                                 [5,6]])

tf.random.shuffle(tensor_exercise1, seed=23)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [20]:
# Exercise 2

tensor_exercise2 = tf.constant([[[1,2],
                                  [3,4]],
                                 [[5,6],
                                  [7,8]],
                                 [[9,10],
                                 [11,12]]])

tf.random.set_seed(12) # global level seed
tf.random.shuffle(tensor_exercise2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [21]:
shuffle_tensor1 = tf.random.shuffle(tensor_exercise2, seed=42)

In [22]:
shuffle_tensor2 = tf.random.shuffle(tensor_exercise2, seed=42)

In [23]:
#check if it equal
shuffle_tensor1 == shuffle_tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=bool, numpy=
array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])>

In [24]:
# Exercise 3

tensor_exercise3 = tf.random.Generator.from_seed(12)
tensor_exercise3 = tensor_exercise3.normal(shape = (3,2))

tensor_exercise3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967],
       [ 0.37944323, -0.6664026 ]], dtype=float32)>

In [25]:
tf.random.shuffle(tensor_exercise3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.37944323, -0.6664026 ],
       [ 1.2132233 ,  0.46988967],
       [-1.0130816 ,  0.28291714]], dtype=float32)>

In [26]:
# Exercise 4

tensor_exercise4 = tf.random.Generator.from_seed(42)
tensor_exercise4 = tensor_exercise4.normal(shape=(4,2,4))

tensor_exercise4

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]]],
      dtype=float32)>

In [27]:
tf.random.shuffle(tensor_exercise4)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]]],
      dtype=float32)>

In [28]:
# Exercise 5

tensor_exercise5 = tf.random.Generator.from_seed(42)
tensor_exercise5 = tensor_exercise5.normal(shape=(2,8,3))

tensor_exercise5

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]]], dtype=float32)>

In [29]:
tf.random.shuffle(tensor_exercise5)

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]],

       [[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]]], dtype=float32)>

### Other ways to create tensor

In [30]:
# create tensor of all ones

tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [31]:
# create tensor of all zeroes

tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main deferent between numpy arrays and tensors is tensors can run in GPU (Fasters)

In [32]:
# You can also turn numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix)  #capital for matrix or tensors
# y = tf.constant(vector)       #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [33]:
A = tf.constant(numpy_A) # its will be tensors
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [34]:
B = tf.constant(numpy_A, shape=(4,3,2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors, we probably want to know the following atribut :
* Shape
* Rank
* Axis or dimension
* Size

In [35]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
# index tensor

rank_4_tensor[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [37]:
# check the shape, rank, and size

rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors

Tensors can be indexing just like pyton list

In [38]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [39]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [40]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [41]:
# Add extra dimension to our tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [42]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [47]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [44]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulating Tensors (Tensor Operation)

**Basic Operation**

In [48]:
# Add values to tensors using addition operation

tensor_op_1 = tf.constant([[10,7],
                           [3,4]])
tensor_op_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [49]:
# check the value
tensor_op_1 # the value dosent change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [50]:
# Multiplication

tensor_op_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [51]:
# Substraction

tensor_op_1 - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-90, -93],
       [-97, -96]], dtype=int32)>

In [52]:
#

tensor_op_1 / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [53]:
# Use the tensorflow built-in function

tf.multiply(tensor_op_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>