<a href="https://colab.research.google.com/github/GabrielBatavia/Learn_TensorFlow/blob/main/00_learn_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# import TensorFlow for first learning

import tensorflow as tf
print(tf.__version__)

2.15.0


In [10]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [12]:
# Create a Vector

vector =  tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
# Check dimensions of the vector

vector.ndim

1

In [14]:
# Create a matrix (has more dimensions)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [15]:
# Check dimensions of the matrix

matrix.ndim

2

In [16]:
# Create another matrix

matrix_2 = tf.constant([[10.2,7.],[7.,10.2],[10.,7.2]], dtype = tf.float16) #spesify data type with parameter
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.2,  7. ],
       [ 7. , 10.2],
       [10. ,  7.2]], dtype=float16)>

In [17]:
# Check dimensions of the other matrix

matrix.ndim

2

In [18]:
# Lets create tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [19]:
tensor.ndim

3

What we create so far?

* Scaler = is a single number
* Vector = a number with direction (e.g wind speed)
* matrix = a 2 dimensional array of numbers
* tensor = an n-dimensional arrays of numbers (n can be any numbers ; 0-dimensional tensor is scaler, 1-dimensional tensor is vector, 2-dimensional tensor is matrix )

### Creating tensor with tf.Variable

In [20]:
# create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
# change the elemen in changeable tensor

# changeable_tensor[0] = 7  #This way will make erorr

#try use .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [22]:
# lets try change unchangeable_tensor

#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

# will make error cause const cant change

What we create so far?

tf.constant = is a constant tensor that we cant change the value
tf.Variable = is a changeable tensor

.assign() = the syntax for change the value of the changeable tensor

### Create random tensors

random tensors are tensors of some abitrary size which contain random numbers

In [23]:
# create two random (but same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [24]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [25]:
#  are they equal?

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [26]:
# shuffle a tensor (valuable if we want shuffle a data so the inherent order dosent effect learning)

not_shuffled = tf.constant([[10,7],
                            [13,2],
                            [7,9]])
#not_shuffled.ndim

# shuffle our non_shuffled tensor
#tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  9],
       [13,  2],
       [10,  7]], dtype=int32)>

⚡**EXERCISE** : read this documentation for set_seed https://www.tensorflow.org/api_docs/python/tf/random/set_seed , and practice writing 5 random tensors and shuffle them

In [27]:
# Exercise 1

tensor_exercise1 = tf.constant([[1,2],
                                 [3,4],
                                 [5,6]])

tf.random.shuffle(tensor_exercise1, seed=23)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [28]:
# Exercise 2

tensor_exercise2 = tf.constant([[[1,2],
                                  [3,4]],
                                 [[5,6],
                                  [7,8]],
                                 [[9,10],
                                 [11,12]]])

tf.random.set_seed(12) # global level seed
tf.random.shuffle(tensor_exercise2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [29]:
shuffle_tensor1 = tf.random.shuffle(tensor_exercise2, seed=42)

In [30]:
shuffle_tensor2 = tf.random.shuffle(tensor_exercise2, seed=42)

In [31]:
#check if it equal
shuffle_tensor1 == shuffle_tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=bool, numpy=
array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])>

In [32]:
# Exercise 3

tensor_exercise3 = tf.random.Generator.from_seed(12)
tensor_exercise3 = tensor_exercise3.normal(shape = (3,2))

tensor_exercise3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0130817 ,  0.28291714],
       [ 1.2132233 ,  0.46988967],
       [ 0.37944326, -0.6664026 ]], dtype=float32)>

In [33]:
tf.random.shuffle(tensor_exercise3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.37944326, -0.6664026 ],
       [ 1.2132233 ,  0.46988967],
       [-1.0130817 ,  0.28291714]], dtype=float32)>

In [34]:
# Exercise 4

tensor_exercise4 = tf.random.Generator.from_seed(42)
tensor_exercise4 = tensor_exercise4.normal(shape=(4,2,4))

tensor_exercise4

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535806 , -0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.44629744, -2.3410842 ,  0.99009085],
        [-0.08763231, -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.5244748 , -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]]],
      dtype=float32)>

In [35]:
tf.random.shuffle(tensor_exercise4)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[ 1.6874489 , -0.44629744, -2.3410842 ,  0.99009085],
        [-0.08763231, -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.5244748 , -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],

       [[-0.7535806 , -0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ,  1.2054597 ]],

       [[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ,  0.09988727, -0.50998646]]],
      dtype=float32)>

In [36]:
# Exercise 5

tensor_exercise5 = tf.random.Generator.from_seed(42)
tensor_exercise5 = tensor_exercise5.normal(shape=(2,8,3))

tensor_exercise5

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ],
        [-0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744],
        [-2.3410842 ,  0.99009085, -0.08763231],
        [-0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.5244748 , -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432486 ],
        [-2.2173238 ,  0.18706241,  0.66179603]]], dtype=float32)>

In [37]:
tf.random.shuffle(tensor_exercise5)

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.48293006, -0.5244748 , -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432486 ],
        [-2.2173238 ,  0.18706241,  0.66179603]],

       [[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ],
        [-0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744],
        [-2.3410842 ,  0.99009085, -0.08763231],
        [-0.635568  , -0.6161736 , -1.9441465 ]]], dtype=float32)>

### Other ways to create tensor

In [38]:
# create tensor of all ones

tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [39]:
# create tensor of all zeroes

tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main deferent between numpy arrays and tensors is tensors can run in GPU (Fasters)

In [40]:
# You can also turn numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix)  #capital for matrix or tensors
# y = tf.constant(vector)       #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [41]:
A = tf.constant(numpy_A) # its will be tensors
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [42]:
B = tf.constant(numpy_A, shape=(4,3,2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors, we probably want to know the following atribut :
* Shape
* Rank
* Axis or dimension
* Size

In [43]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
# index tensor

rank_4_tensor[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [45]:
# check the shape, rank, and size

rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors

Tensors can be indexing just like pyton list

In [46]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [47]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [48]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [49]:
# Add extra dimension to our tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [50]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [51]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [52]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulating Tensors (Tensor Operation)

**Basic Operation**

In [53]:
# Add values to tensors using addition operation

tensor_op_1 = tf.constant([[10,7],
                           [3,4]])
tensor_op_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [54]:
# check the value
tensor_op_1 # the value dosent change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [55]:
# Multiplication

tensor_op_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [56]:
# Substraction

tensor_op_1 - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-90, -93],
       [-97, -96]], dtype=int32)>

In [57]:
#

tensor_op_1 / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [58]:
# Use the tensorflow built-in function

tf.multiply(tensor_op_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multipication

In machine learning, matrix multipication is one common tensor operations

Two rules :
1. The inner dimensions must match
2. The resulting matrix has shape of the outer dimensions

for the example : if we have 3,2 and 2,3 matrix <br>
the "3" from the first matrix and "3" from the second is the outer<br>
the "2" from the first matrix and "2" from the second is the inner

In [59]:
 # Matrix multiplication in tensorflow

 print(tensor_op_1)
 tf.matmul(tensor_op_1, tensor_op_1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [60]:
# Matrix multiplication with Python operatot "@"

tensor_op_1 @ tensor_op_1

# Just can use if the matrix shape([2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [61]:
# create a example tensor (little exercise)

tensor1 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])

tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])

In [62]:
# multyply the tensor

tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [63]:
# try to reshape

tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [64]:
# We can do same with transpose

tf.transpose(tensor2) # have deferent output from the reshape cause its flip the axis

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [65]:
# try by my self

tf.matmul(tf.transpose(tensor1), tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 24, 33],
       [21, 21, 21],
       [22, 40, 27]], dtype=int32)>

### The dot Product

Matrix multiplication is also referred to as the dot product

We can perform matrix multiplication with :
* `tf.matmul()`
* `tf.tensordot()`

In [66]:
# make the tensor first

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [67]:
# Perform the dot product  on X and Y (requires the X and Y to be transposed)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [68]:
# Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [69]:
# Perform matrix multiplication between X and Y (reshape)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [70]:
# Check the values of Y, reshape Y and transpose Y

print("Normal Y:")
print(Y, "\n ")

print("Y reshaped to (2, 3) :")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed :")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 
 
Y reshaped to (2, 3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing multiplication, we will transpose (rather than reshape)

###  Changing the datatype of a tensor

In [71]:
tf.__version__

'2.15.0'

In [72]:
# create new tensor with default datatype (float32)

A = tf.constant([1.2, 5.7])
A.dtype


tf.float32

In [73]:
# create new tensor with default datatype (int32)

B = tf.constant([2,3])
B.dtype

tf.int32

In [74]:
# Change from float32 to float16 (reduced precision)

A = tf.cast(A, dtype=tf.float16)
A.dtype

tf.float16

In [75]:
# Change ftom int32 to int16

B = tf.cast(B, dtype=tf.int16)
B.dtype

tf.int16

### Aggregating Tensors

Aggregating tensors = condesing them from multiple values down to a smaller amount of values

In [76]:
# Get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [77]:
# Get the absolute values

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Following forms of aggregation :**

* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [78]:
# Find the min

tf.math.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [79]:
# Find the max

tf.math.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [80]:
# find the mean

tf.math.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [81]:
# Find the sum

tf.math.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [82]:
# create random tensor with values between 0 and 100

random_tensor = tf.constant(np.random.randint(0,100, size=150))
random_tensor

<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([69, 38, 97, 18,  7, 62,  8,  6, 89, 35, 63, 54, 94, 58, 58,  0, 99,
       43, 29,  2, 91, 40, 40, 83, 99, 52, 22, 73, 10, 73, 91, 96, 69, 55,
       71, 49, 85, 54, 95, 19, 34, 74, 75, 91, 69, 18, 57, 94, 73,  3, 77,
       29, 89, 69, 16,  3, 89, 12, 76, 16, 25, 90, 21, 75, 29, 45, 48,  7,
       63, 24, 38, 63, 57, 94, 41, 40, 25, 46, 13, 51, 73, 48, 12, 35, 67,
       35, 57, 54, 26, 68, 73, 13, 77, 37, 42, 70, 56, 55, 71, 31, 47, 84,
       89, 62, 35, 57, 60, 74, 32, 37,  7,  0, 51, 24, 63, 16,  3, 52, 63,
       62, 87, 68, 52, 85, 88, 36, 51, 99, 24, 68, 56, 92, 58, 61, 42,  0,
       95, 23, 70, 38, 65, 61, 57, 93, 14, 91, 51, 12, 54, 66])>

In [83]:
tf.size(random_tensor), random_tensor.ndim, random_tensor.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=150>, 1, TensorShape([150]))

In [84]:
# Find the min

tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [85]:
# Find the max

tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [86]:
# Find the mean

tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [87]:
# Find the sum

tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=7830>

⚡**EXERCISE** : Find the variance and standard deviation of our random_tensor

In [88]:
# import tfp for find variance

import tensorflow_probability as tfp

In [89]:
# Find the variance

tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=757>

In [90]:
# but we can just use tf to find variance but its must in float (real or complex tensor)

tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=757.1466666666666>

In [91]:
# Find the standard deviation

tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=27.516298200642225>

### Find the Positional maximum and minimum

In [92]:
# create new tensor

tensorA = tf.constant(np.random.randint(0,15, size=50))
tensorA

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([10, 11,  0,  5, 10,  5,  6, 14,  6,  1,  5, 14, 12,  6,  8,  0,  0,
       11,  0,  3, 14,  1,  6,  4, 14,  0,  9,  6,  8,  2, 14,  1,  6,  1,
        3, 12,  7,  0,  7,  8, 11,  4, 13, 14, 10,  0,  3,  9,  6,  5])>

In [93]:
# Find positional maximum

tf.argmax(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [94]:
# index the large value

tensorA[tf.argmax(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [95]:
# Find positional minimum

tf.argmin(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [96]:
# Index the smallest value

tensorA[tf.argmin(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [97]:
# just create a random tensor

random1 = tf.constant(np.random.randint(0, 15, size=10))
random2 = tf.constant(np.random.randint(0,15, size=10))

print(random1, random2)

tf.Tensor([ 0  8 13  9  5 11  9  4  1  2], shape=(10,), dtype=int64) tf.Tensor([ 8  2 10  0  8  5  5  8 10  4], shape=(10,), dtype=int64)


In [98]:
# Find positional maximum

tf.math.maximum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 8,  8, 13,  9,  8, 11,  9,  8, 10,  4])>

In [99]:
# Find positional minimum

tf.math.minimum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 0,  2, 10,  0,  5,  5,  5,  4,  1,  2])>

In [100]:
# create more example

random3 = tf.constant([[[1,2],
                       [3,8]],
                       [[9,2],
                        [7,3]]])

random4 = tf.constant([[[3,8],
                       [9,10]],
                       [[29,4],
                        [4,8]]])

random3, random4

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 8]],
 
        [[9, 2],
         [7, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 3,  8],
         [ 9, 10]],
 
        [[29,  4],
         [ 4,  8]]], dtype=int32)>)

In [101]:
# Find positional maximum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

In [102]:
# Find positional minimum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

### Squeezing a tensor (removing all single dimensions)

In [103]:
# Create a tensor to get started

G = tf.constant(tf.random.uniform(shape=[50]), shape=(2, 1, 1, 1, 25))
G

<tf.Tensor: shape=(2, 1, 1, 1, 25), dtype=float32, numpy=
array([[[[[0.79978   , 0.8948238 , 0.39822733, 0.39745378, 0.07829857,
           0.16906297, 0.04041338, 0.94953513, 0.24754536, 0.8756521 ,
           0.3054012 , 0.05631793, 0.78040993, 0.36824238, 0.02072537,
           0.5164361 , 0.90202785, 0.4387293 , 0.2045883 , 0.18139648,
           0.84017384, 0.96967316, 0.6941571 , 0.02483487, 0.8024013 ]]]],



       [[[[0.24896455, 0.94637156, 0.08169639, 0.26656103, 0.7582942 ,
           0.1050272 , 0.9802648 , 0.3198321 , 0.814749  , 0.79346156,
           0.8850808 , 0.00581694, 0.0769527 , 0.7721684 , 0.35605192,
           0.7837372 , 0.69836867, 0.93739164, 0.21395409, 0.12435579,
           0.21066833, 0.95097876, 0.9655094 , 0.76438355, 0.9313054 ]]]]],
      dtype=float32)>

In [104]:
G.shape

TensorShape([2, 1, 1, 1, 25])

In [105]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.79978   , 0.8948238 , 0.39822733, 0.39745378, 0.07829857,
         0.16906297, 0.04041338, 0.94953513, 0.24754536, 0.8756521 ,
         0.3054012 , 0.05631793, 0.78040993, 0.36824238, 0.02072537,
         0.5164361 , 0.90202785, 0.4387293 , 0.2045883 , 0.18139648,
         0.84017384, 0.96967316, 0.6941571 , 0.02483487, 0.8024013 ],
        [0.24896455, 0.94637156, 0.08169639, 0.26656103, 0.7582942 ,
         0.1050272 , 0.9802648 , 0.3198321 , 0.814749  , 0.79346156,
         0.8850808 , 0.00581694, 0.0769527 , 0.7721684 , 0.35605192,
         0.7837372 , 0.69836867, 0.93739164, 0.21395409, 0.12435579,
         0.21066833, 0.95097876, 0.9655094 , 0.76438355, 0.9313054 ]],
       dtype=float32)>,
 TensorShape([2, 25]))

### One-hot encoding

In [106]:
# Create a list of indices

some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices\
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [107]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="i also like shalom")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like shalom',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'yo i love deep learning',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'yo i love deep learning', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'yo i love deep learning']], dtype=object)>

In [108]:
# Create my own list for little exercise

listRandom = [0, 1, 2, 3, 4, 5]

# one hot encode
tf.one_hot(listRandom, depth=7)

<tf.Tensor: shape=(6, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [109]:
# custom one hot

tf.one_hot(listRandom, depth=7,on_value="i love shalom" ,off_value = "i love machine learning", axis=1, name="List of i love")

<tf.Tensor: shape=(6, 7), dtype=string, numpy=
array([[b'i love shalom', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love shalom',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i love shalom', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love shalom',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i l

### Squaring, log, square root

In [110]:
# Create a new tensor

tensorH = tf.range(1, 10)
tensorH

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [111]:
# Square it

tf.square(tensorH)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [112]:
# we have change the data type cause squareroot and log dosent allow int

tensorH = tf.cast(tensorH, dtype=tf.float32)

In [113]:
# Find the squareroot

tf.math.sqrt(tensorH)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [114]:
# Find the log

tf.math.log(tensorH)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Exercise by my self**

practice 3 method from tf.math model

In [115]:
# create new tensor for our example

x = tf.constant([[1,2]
                ,[3,4]])

y = tf.constant([[5,6],
                [7,8]])

In [116]:
# try tf.math.asin

tf.math.asin(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.5707964,       nan],
       [      nan,       nan]], dtype=float32)>

In [117]:
# try tf.math.sin

tf.math.sin(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.841471  ,  0.90929747],
       [ 0.14112   , -0.7568025 ]], dtype=float32)>

In [118]:
# try tf.math.tan

tf.math.tan(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.5574079 , -2.18504   ],
       [-0.14254653,  1.1578213 ]], dtype=float32)>

### Tensors and Numpy

TensorFlow interact beautifully with Numpy arrays

In [119]:
# Create a tensor directly with numpy arrays

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [120]:
# Convert our tensor back to a Numpy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [121]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [122]:
# The default types of each are slightly defferent

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# check the datatype

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [123]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [124]:
!nvidia-smi

Sat Mar 23 14:23:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   63C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

🔑 **NOTE :** if you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenver possible

## 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Multiply the two tensors you created in 3 using dot product.

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.

In [125]:
# Create vector, scalar, matrix, and tensor

vector_ex = tf.constant(7)

scalar_ex = tf.constant([2, 3, 4])

matrix_ex = tf.constant([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_ex = tf.constant([[[1,2],
                          [3,4]],
                         [[5,6],
                          [7,8]],
                         [[8,9],
                          [10,11]]])

vector_ex, scalar_ex, matrix_ex, tensor_ex

(<tf.Tensor: shape=(), dtype=int32, numpy=7>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 8,  9],
         [10, 11]]], dtype=int32)>)

In [126]:
# find shape rank and size

tensor_ex.shape, tensor_ex.ndim, tf.size(tensor_ex)

(TensorShape([3, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [127]:
# Create two tensors random

zero_tensor = tf.zeros([5, 300])
one_tensor = tf.ones([5, 300])

zero_tensor, one_tensor

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>)

In [128]:
# Multiply two tensors

zero_tensor * one_tensor # use reguler operation

tf.multiply(zero_tensor, one_tensor)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

In [129]:
# dot two tensor

tf.tensordot(zero_tensor, tf.transpose(one_tensor), axes=1)


<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [154]:
# create tensor wandom value between 0 and 1

random_1 = tf.constant(tf.random.uniform(shape=[224,224,3], minval=0, maxval=1, dtype=tf.float32))
random_1


<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5440587 , 0.14025676, 0.42364144],
        [0.9044055 , 0.16143632, 0.7203022 ],
        [0.0750035 , 0.6840236 , 0.13792026],
        ...,
        [0.9799608 , 0.388471  , 0.21754444],
        [0.89100504, 0.24424362, 0.5971441 ],
        [0.44113374, 0.84884167, 0.93080163]],

       [[0.5545393 , 0.95801854, 0.8646561 ],
        [0.35564506, 0.66211843, 0.6553854 ],
        [0.2881819 , 0.17633939, 0.23181784],
        ...,
        [0.3231598 , 0.3221681 , 0.33023667],
        [0.979681  , 0.6003238 , 0.09332955],
        [0.22685742, 0.6463547 , 0.24337602]],

       [[0.6523129 , 0.52970684, 0.8255924 ],
        [0.74986815, 0.19473553, 0.7345443 ],
        [0.874555  , 0.20370924, 0.93235385],
        ...,
        [0.15743732, 0.4116298 , 0.25211084],
        [0.04690337, 0.03855467, 0.990201  ],
        [0.92177737, 0.74582875, 0.5995414 ]],

       ...,

       [[0.38686728, 0.3553337 , 0.6434274 ],
        [0.57

In [156]:
# Find min and max

print(tf.reduce_min(random_1[0]))
print(tf.reduce_max(random_1[0]))

tf.Tensor(0.00071287155, shape=(), dtype=float32)
tf.Tensor(0.999678, shape=(), dtype=float32)


In [157]:
# Create the random tensor

# tensor_generator = tf.random.Generator.from_seed(42)
# tensor_generator1 = tensor_generator.uniform(shape=(1, 224, 224, 3))
# tensor_generator1

# Another way
tensor_generator1 = tf.constant(tf.random.uniform(shape=[1,224,224,3], minval=1, maxval=10, dtype=tf.float32))
tensor_generator1


<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[4.9639034, 1.8541366, 1.3856952],
         [8.969077 , 1.4168067, 7.766918 ],
         [6.3610287, 8.116631 , 2.7791982],
         ...,
         [1.8797088, 8.326624 , 3.9523418],
         [8.19106  , 7.3617373, 6.0968356],
         [9.864975 , 6.443257 , 3.5367732]],

        [[3.0391002, 8.033046 , 9.004246 ],
         [1.854996 , 6.2106   , 3.1138477],
         [5.930456 , 9.978542 , 3.8891554],
         ...,
         [5.25346  , 2.355404 , 8.99862  ],
         [7.6699233, 8.734317 , 8.469535 ],
         [4.747901 , 5.864997 , 4.111281 ]],

        [[3.6835833, 6.230318 , 9.800886 ],
         [4.424217 , 8.129711 , 1.9563481],
         [3.2603984, 9.647714 , 8.650385 ],
         ...,
         [5.2977777, 9.887447 , 8.59228  ],
         [3.593122 , 7.8184843, 9.964281 ],
         [8.954787 , 2.736433 , 3.0164924]],

        ...,

        [[2.0865316, 7.9941864, 9.792606 ],
         [7.075527 , 2.3855743, 1.8126278],


In [158]:
# Squeezing the tensor

tf.squeeze(tensor_generator1)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[4.9639034, 1.8541366, 1.3856952],
        [8.969077 , 1.4168067, 7.766918 ],
        [6.3610287, 8.116631 , 2.7791982],
        ...,
        [1.8797088, 8.326624 , 3.9523418],
        [8.19106  , 7.3617373, 6.0968356],
        [9.864975 , 6.443257 , 3.5367732]],

       [[3.0391002, 8.033046 , 9.004246 ],
        [1.854996 , 6.2106   , 3.1138477],
        [5.930456 , 9.978542 , 3.8891554],
        ...,
        [5.25346  , 2.355404 , 8.99862  ],
        [7.6699233, 8.734317 , 8.469535 ],
        [4.747901 , 5.864997 , 4.111281 ]],

       [[3.6835833, 6.230318 , 9.800886 ],
        [4.424217 , 8.129711 , 1.9563481],
        [3.2603984, 9.647714 , 8.650385 ],
        ...,
        [5.2977777, 9.887447 , 8.59228  ],
        [3.593122 , 7.8184843, 9.964281 ],
        [8.954787 , 2.736433 , 3.0164924]],

       ...,

       [[2.0865316, 7.9941864, 9.792606 ],
        [7.075527 , 2.3855743, 1.8126278],
        [1.8689327, 5.62443

In [166]:
# create the tensor

tensor_ex9 = tf.constant(tf.random.uniform([10], 0, 10))
tensor_ex9, tensor_ex9[tf.argmax(tensor_ex9)]

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([1.6484797 , 7.097478  , 7.0350704 , 4.243922  , 4.0026855 ,
        9.00853   , 5.88547   , 8.209631  , 4.2019835 , 0.28244972],
       dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=9.00853>)

In [168]:
# One-hot encode

tf.one_hot(tf.cast(tensor_ex9, dtype=tf.int32), depth=10)



<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [169]:
# bonus onehot encode

tf.one_hot(tf.cast(tensor_ex9, dtype=tf.int32), depth=10, on_value="yo i love deep learning", off_value="i also like shalom")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'i also like shalom', b'yo i love deep learning',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'yo i love deep learning',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'yo i love deep learning',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'i also like shalom',
        b'yo i 