<a href="https://colab.research.google.com/github/GabrielBatavia/Learn_TensorFlow/blob/main/00_learn_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [197]:
# import TensorFlow for first learning

import tensorflow as tf
print(tf.__version__)

2.15.0


In [198]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [199]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [200]:
# Create a Vector

vector =  tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [201]:
# Check dimensions of the vector

vector.ndim

1

In [202]:
# Create a matrix (has more dimensions)

matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [203]:
# Check dimensions of the matrix

matrix.ndim

2

In [204]:
# Create another matrix

matrix_2 = tf.constant([[10.2,7.],[7.,10.2],[10.,7.2]], dtype = tf.float16) #spesify data type with parameter
matrix_2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.2,  7. ],
       [ 7. , 10.2],
       [10. ,  7.2]], dtype=float16)>

In [205]:
# Check dimensions of the other matrix

matrix.ndim

2

In [206]:
# Lets create tensor

tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [207]:
tensor.ndim

3

What we create so far?

* Scaler = is a single number
* Vector = a number with direction (e.g wind speed)
* matrix = a 2 dimensional array of numbers
* tensor = an n-dimensional arrays of numbers (n can be any numbers ; 0-dimensional tensor is scaler, 1-dimensional tensor is vector, 2-dimensional tensor is matrix )

### Creating tensor with tf.Variable

In [208]:
# create the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [209]:
# change the elemen in changeable tensor

# changeable_tensor[0] = 7  #This way will make erorr

#try use .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [210]:
# lets try change unchangeable_tensor

#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

# will make error cause const cant change

What we create so far?

tf.constant = is a constant tensor that we cant change the value
tf.Variable = is a changeable tensor

.assign() = the syntax for change the value of the changeable tensor

### Create random tensors

random tensors are tensors of some abitrary size which contain random numbers

In [211]:
# create two random (but same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape = (3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [212]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [213]:
#  are they equal?

random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in a tensor

In [214]:
# shuffle a tensor (valuable if we want shuffle a data so the inherent order dosent effect learning)

not_shuffled = tf.constant([[10,7],
                            [13,2],
                            [7,9]])
#not_shuffled.ndim

# shuffle our non_shuffled tensor
#tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  9],
       [10,  7],
       [13,  2]], dtype=int32)>

⚡**EXERCISE** : read this documentation for set_seed https://www.tensorflow.org/api_docs/python/tf/random/set_seed , and practice writing 5 random tensors and shuffle them

In [215]:
# Exercise 1

tensor_exercise1 = tf.constant([[1,2],
                                 [3,4],
                                 [5,6]])

tf.random.shuffle(tensor_exercise1, seed=23)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [216]:
# Exercise 2

tensor_exercise2 = tf.constant([[[1,2],
                                  [3,4]],
                                 [[5,6],
                                  [7,8]],
                                 [[9,10],
                                 [11,12]]])

tf.random.set_seed(12) # global level seed
tf.random.shuffle(tensor_exercise2)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 5,  6],
        [ 7,  8]],

       [[ 1,  2],
        [ 3,  4]],

       [[ 9, 10],
        [11, 12]]], dtype=int32)>

In [217]:
shuffle_tensor1 = tf.random.shuffle(tensor_exercise2, seed=42)

In [218]:
shuffle_tensor2 = tf.random.shuffle(tensor_exercise2, seed=42)

In [219]:
#check if it equal
shuffle_tensor1 == shuffle_tensor2

<tf.Tensor: shape=(3, 2, 2), dtype=bool, numpy=
array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])>

In [220]:
# Exercise 3

tensor_exercise3 = tf.random.Generator.from_seed(12)
tensor_exercise3 = tensor_exercise3.normal(shape = (3,2))

tensor_exercise3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.0130816 ,  0.28291714],
       [ 1.2132233 ,  0.46988967],
       [ 0.37944323, -0.6664026 ]], dtype=float32)>

In [221]:
tf.random.shuffle(tensor_exercise3)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.37944323, -0.6664026 ],
       [ 1.2132233 ,  0.46988967],
       [-1.0130816 ,  0.28291714]], dtype=float32)>

In [222]:
# Exercise 4

tensor_exercise4 = tf.random.Generator.from_seed(42)
tensor_exercise4 = tensor_exercise4.normal(shape=(4,2,4))

tensor_exercise4

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]]],
      dtype=float32)>

In [223]:
tf.random.shuffle(tensor_exercise4)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[ 1.6874489 , -0.4462975 , -2.3410842 ,  0.99009085],
        [-0.0876323 , -0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ,  1.3066901 ],
        [-1.5184573 , -0.4585211 ,  0.5714663 , -1.5331722 ]],

       [[-0.7535805 , -0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ,  1.2054597 ]],

       [[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646]]],
      dtype=float32)>

In [224]:
# Exercise 5

tensor_exercise5 = tf.random.Generator.from_seed(42)
tensor_exercise5 = tensor_exercise5.normal(shape=(2,8,3))

tensor_exercise5

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]],

       [[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]]], dtype=float32)>

In [225]:
tf.random.shuffle(tensor_exercise5)

<tf.Tensor: shape=(2, 8, 3), dtype=float32, numpy=
array([[[-0.48293006, -0.52447474, -1.0345329 ],
        [ 1.3066901 , -1.5184573 , -0.4585211 ],
        [ 0.5714663 , -1.5331722 ,  0.45331386],
        [ 1.1487608 , -1.2659091 , -0.47450137],
        [ 2.006022  ,  0.28288034, -0.30288252],
        [-1.443651  ,  1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ,  1.2432485 ],
        [-2.2173238 ,  0.18706243,  0.6617961 ]],

       [[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993],
        [-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ],
        [-2.3410842 ,  0.99009085, -0.0876323 ],
        [-0.635568  , -0.6161736 , -1.9441465 ]]], dtype=float32)>

### Other ways to create tensor

In [226]:
# create tensor of all ones

tf.ones([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [227]:
# create tensor of all zeroes

tf.zeros(shape=(3,5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn numpy arrays into tensors

The main deferent between numpy arrays and tensors is tensors can run in GPU (Fasters)

In [228]:
# You can also turn numpy arrays into tensors

import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # create numpy array between 1 and 25
numpy_A

# x = tf.constant(some_matrix)  #capital for matrix or tensors
# y = tf.constant(vector)       #non capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [229]:
A = tf.constant(numpy_A) # its will be tensors
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [230]:
B = tf.constant(numpy_A, shape=(4,3,2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

### Getting information from tensors

When dealing with tensors, we probably want to know the following atribut :
* Shape
* Rank
* Axis or dimension
* Size

In [231]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [232]:
# index tensor

rank_4_tensor[0,0,0,0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [233]:
# check the shape, rank, and size

rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensors

Tensors can be indexing just like pyton list

In [234]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [235]:
# create rank 2 tensor
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [236]:
# Get the last item of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [237]:
# Add extra dimension to our tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [238]:
rank_2_tensor.ndim, rank_3_tensor.ndim

(2, 3)

In [239]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [240]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Manipulating Tensors (Tensor Operation)

**Basic Operation**

In [241]:
# Add values to tensors using addition operation

tensor_op_1 = tf.constant([[10,7],
                           [3,4]])
tensor_op_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [242]:
# check the value
tensor_op_1 # the value dosent change

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [243]:
# Multiplication

tensor_op_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [244]:
# Substraction

tensor_op_1 - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-90, -93],
       [-97, -96]], dtype=int32)>

In [245]:
#

tensor_op_1 / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

In [246]:
# Use the tensorflow built-in function

tf.multiply(tensor_op_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multipication

In machine learning, matrix multipication is one common tensor operations

Two rules :
1. The inner dimensions must match
2. The resulting matrix has shape of the outer dimensions

for the example : if we have 3,2 and 2,3 matrix <br>
the "3" from the first matrix and "3" from the second is the outer<br>
the "2" from the first matrix and "2" from the second is the inner

In [247]:
 # Matrix multiplication in tensorflow

 print(tensor_op_1)
 tf.matmul(tensor_op_1, tensor_op_1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [248]:
# Matrix multiplication with Python operatot "@"

tensor_op_1 @ tensor_op_1

# Just can use if the matrix shape([2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [249]:
# create a example tensor (little exercise)

tensor1 = tf.constant([[1,2,5],
                       [7,2,1],
                       [3,3,3]])

tensor2 = tf.constant([[3,5],
                       [6,7],
                       [1,8]])

In [250]:
# multyply the tensor

tf.matmul(tensor1, tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [251]:
# try to reshape

tf.reshape(tensor2, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [252]:
# We can do same with transpose

tf.transpose(tensor2) # have deferent output from the reshape cause its flip the axis

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [253]:
# try by my self

tf.matmul(tf.transpose(tensor1), tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[30, 24, 33],
       [21, 21, 21],
       [22, 40, 27]], dtype=int32)>

### The dot Product

Matrix multiplication is also referred to as the dot product

We can perform matrix multiplication with :
* `tf.matmul()`
* `tf.tensordot()`

In [254]:
# make the tensor first

X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [255]:
# Perform the dot product  on X and Y (requires the X and Y to be transposed)

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [256]:
# Perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [257]:
# Perform matrix multiplication between X and Y (reshape)

tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [258]:
# Check the values of Y, reshape Y and transpose Y

print("Normal Y:")
print(Y, "\n ")

print("Y reshaped to (2, 3) :")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed :")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 
 
Y reshaped to (2, 3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing multiplication, we will transpose (rather than reshape)

###  Changing the datatype of a tensor

In [259]:
tf.__version__

'2.15.0'

In [260]:
# create new tensor with default datatype (float32)

A = tf.constant([1.2, 5.7])
A.dtype


tf.float32

In [261]:
# create new tensor with default datatype (int32)

B = tf.constant([2,3])
B.dtype

tf.int32

In [262]:
# Change from float32 to float16 (reduced precision)

A = tf.cast(A, dtype=tf.float16)
A.dtype

tf.float16

In [263]:
# Change ftom int32 to int16

B = tf.cast(B, dtype=tf.int16)
B.dtype

tf.int16

### Aggregating Tensors

Aggregating tensors = condesing them from multiple values down to a smaller amount of values

In [264]:
# Get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [265]:
# Get the absolute values

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

**Following forms of aggregation :**

* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [266]:
# Find the min

tf.math.reduce_min(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [267]:
# Find the max

tf.math.reduce_max(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-7>

In [268]:
# find the mean

tf.math.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [269]:
# Find the sum

tf.math.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-17>

In [270]:
# create random tensor with values between 0 and 100

random_tensor = tf.constant(np.random.randint(0,100, size=150))
random_tensor

<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([83, 32, 34, 97, 20, 52, 77,  1, 80, 72, 55, 69, 16, 42, 51, 67, 79,
       90, 60, 51, 22, 55, 46, 58, 76, 23, 76, 47, 25, 85, 80, 71, 42, 62,
       85, 25, 18, 21, 31,  3, 77,  2, 36, 20, 35,  1, 77, 18, 54,  2, 25,
        7, 94, 22, 65, 23, 24, 85,  3, 99,  1, 89,  3, 29, 29, 18, 80, 44,
       30, 40, 14, 41, 20, 90,  8, 30,  5, 57, 95,  5, 93, 41,  1, 34, 17,
       17, 96, 31, 63, 76, 89,  8, 12, 54,  2, 13, 44, 57,  0, 90, 80, 73,
       38, 66,  4, 83, 69, 86, 66, 93, 36, 15, 58, 75,  5, 44, 30, 57, 73,
       28, 99, 48, 65,  5,  0, 60, 86, 96, 20, 62, 52, 27, 39, 44, 20, 30,
       95, 44, 49, 17, 46, 52, 31, 33, 31, 86, 56,  7, 40, 31])>

In [271]:
tf.size(random_tensor), random_tensor.ndim, random_tensor.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=150>, 1, TensorShape([150]))

In [272]:
# Find the min

tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [273]:
# Find the max

tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [274]:
# Find the mean

tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [275]:
# Find the sum

tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=6864>

⚡**EXERCISE** : Find the variance and standard deviation of our random_tensor

In [276]:
# import tfp for find variance

import tensorflow_probability as tfp

In [277]:
# Find the variance

tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=850>

In [278]:
# but we can just use tf to find variance but its must in float (real or complex tensor)

tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=849.7957333333334>

In [279]:
# Find the standard deviation

tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=29.151256119305277>

### Find the Positional maximum and minimum

In [280]:
# create new tensor

tensorA = tf.constant(np.random.randint(0,15, size=50))
tensorA

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 4, 12,  9, 14,  0,  9,  6, 12,  5,  6, 14,  4, 13, 10,  2,  6,  3,
       10,  1,  0, 11, 14,  4,  2,  8, 13, 11, 10, 13, 10,  6, 14,  4,  6,
        5, 12,  1, 12,  0,  6, 12,  6,  6,  5,  0,  5,  7, 10,  7, 10])>

In [281]:
# Find positional maximum

tf.argmax(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [282]:
# index the large value

tensorA[tf.argmax(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=14>

In [283]:
# Find positional minimum

tf.argmin(tensorA)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [284]:
# Index the smallest value

tensorA[tf.argmin(tensorA)]

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [285]:
# just create a random tensor

random1 = tf.constant(np.random.randint(0, 15, size=10))
random2 = tf.constant(np.random.randint(0,15, size=10))

print(random1, random2)

tf.Tensor([12  1  5 11  3  8  6 13  0  3], shape=(10,), dtype=int64) tf.Tensor([12  3  7  9 14  5 10  5  4  4], shape=(10,), dtype=int64)


In [286]:
# Find positional maximum

tf.math.maximum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([12,  3,  7, 11, 14,  8, 10, 13,  4,  4])>

In [287]:
# Find positional minimum

tf.math.minimum(random1, random2)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([12,  1,  5,  9,  3,  5,  6,  5,  0,  3])>

In [288]:
# create more example

random3 = tf.constant([[[1,2],
                       [3,8]],
                       [[9,2],
                        [7,3]]])

random4 = tf.constant([[[3,8],
                       [9,10]],
                       [[29,4],
                        [4,8]]])

random3, random4

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 8]],
 
        [[9, 2],
         [7, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[ 3,  8],
         [ 9, 10]],
 
        [[29,  4],
         [ 4,  8]]], dtype=int32)>)

In [289]:
# Find positional maximum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

In [290]:
# Find positional minimum

tf.math.maximum(random3, random4)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 3,  8],
        [ 9, 10]],

       [[29,  4],
        [ 7,  8]]], dtype=int32)>

### Squeezing a tensor (removing all single dimensions)

In [291]:
# Create a tensor to get started

G = tf.constant(tf.random.uniform(shape=[50]), shape=(2, 1, 1, 1, 25))
G

<tf.Tensor: shape=(2, 1, 1, 1, 25), dtype=float32, numpy=
array([[[[[0.79978   , 0.8948238 , 0.39822733, 0.39745378, 0.07829857,
           0.16906297, 0.04041338, 0.94953513, 0.24754536, 0.8756521 ,
           0.3054012 , 0.05631793, 0.78040993, 0.36824238, 0.02072537,
           0.5164361 , 0.90202785, 0.4387293 , 0.2045883 , 0.18139648,
           0.84017384, 0.96967316, 0.6941571 , 0.02483487, 0.8024013 ]]]],



       [[[[0.24896455, 0.94637156, 0.08169639, 0.26656103, 0.7582942 ,
           0.1050272 , 0.9802648 , 0.3198321 , 0.814749  , 0.79346156,
           0.8850808 , 0.00581694, 0.0769527 , 0.7721684 , 0.35605192,
           0.7837372 , 0.69836867, 0.93739164, 0.21395409, 0.12435579,
           0.21066833, 0.95097876, 0.9655094 , 0.76438355, 0.9313054 ]]]]],
      dtype=float32)>

In [292]:
G.shape

TensorShape([2, 1, 1, 1, 25])

In [293]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.79978   , 0.8948238 , 0.39822733, 0.39745378, 0.07829857,
         0.16906297, 0.04041338, 0.94953513, 0.24754536, 0.8756521 ,
         0.3054012 , 0.05631793, 0.78040993, 0.36824238, 0.02072537,
         0.5164361 , 0.90202785, 0.4387293 , 0.2045883 , 0.18139648,
         0.84017384, 0.96967316, 0.6941571 , 0.02483487, 0.8024013 ],
        [0.24896455, 0.94637156, 0.08169639, 0.26656103, 0.7582942 ,
         0.1050272 , 0.9802648 , 0.3198321 , 0.814749  , 0.79346156,
         0.8850808 , 0.00581694, 0.0769527 , 0.7721684 , 0.35605192,
         0.7837372 , 0.69836867, 0.93739164, 0.21395409, 0.12435579,
         0.21066833, 0.95097876, 0.9655094 , 0.76438355, 0.9313054 ]],
       dtype=float32)>,
 TensorShape([2, 25]))

### One-hot encoding

In [295]:
# Create a list of indices

some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices\
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [296]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="i also like shalom")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like shalom',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'yo i love deep learning',
        b'i also like shalom', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'yo i love deep learning', b'i also like shalom'],
       [b'i also like shalom', b'i also like shalom',
        b'i also like shalom', b'yo i love deep learning']], dtype=object)>

In [308]:
# Create my own list for little exercise

listRandom = [0, 1, 2, 3, 4, 5]

# one hot encode
tf.one_hot(listRandom, depth=7)

<tf.Tensor: shape=(6, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [309]:
# custom one hot

tf.one_hot(listRandom, depth=7,on_value="i love shalom" ,off_value = "i love machine learning", axis=1, name="List of i love")

<tf.Tensor: shape=(6, 7), dtype=string, numpy=
array([[b'i love shalom', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love shalom',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i love shalom', b'i love machine learning',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i love machine learning', b'i love shalom',
        b'i love machine learning', b'i love machine learning',
        b'i love machine learning'],
       [b'i love machine learning', b'i love machine learning',
        b'i l

### Squaring, log, square root

In [310]:
# Create a new tensor

tensorH = tf.range(1, 10)
tensorH

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [311]:
# Square it

tf.square(tensorH)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [316]:
# we have change the data type cause squareroot and log dosent allow int

tensorH = tf.cast(tensorH, dtype=tf.float32)

In [317]:
# Find the squareroot

tf.math.sqrt(tensorH)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [318]:
# Find the log

tf.math.log(tensorH)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Exercise by my self**

practice 3 method from tf.math model

In [320]:
# create new tensor for our example

x = tf.constant([[1,2]
                ,[3,4]])

y = tf.constant([[5,6],
                [7,8]])

In [324]:
# try tf.math.asin

tf.math.asin(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.5707964,       nan],
       [      nan,       nan]], dtype=float32)>

In [325]:
# try tf.math.sin

tf.math.sin(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.84147096,  0.9092974 ],
       [ 0.14112   , -0.7568025 ]], dtype=float32)>

In [326]:
# try tf.math.tan

tf.math.tan(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.5574077 , -2.1850398 ],
       [-0.14254655,  1.1578213 ]], dtype=float32)>